### ISSUE TITLE
希望能提供在 APP.js 中可以设置全局的 globalData 的方法

### ISSUE THREAD

**Issue by Itarn** [WozHuang/mp-extend#1]
globalData 的默认数值，一般不是静态的，需要执行某个方法或者像后端请求完才能获得。问题是，如果执行获取某个 globalData 的方法是在 APP.js 中，好像没有相关的 API 可以使用。

**Comment by WozHuang** [comment]
已经为 App 加上了 $globalSetData 的方法，谢谢你的issue  :laughing:
